name: tutorialx
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  supabase: ^2.6.1
  http: ^1.2.2
  get: ^4.6.6
  flutter_riverpod: ^2.6.1
  provider: any
  get_it: ^8.0.3
  auto_route: ^9.2.2
  flutter_bloc: ^8.1.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
